services:
  postgres-db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=quicktube_db
    ports:
      - "5434:5432"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
